    "||作用|\n",
    "|-|-|\n",
    "|1|**基本属性**\n",
    "|`a.dtype`|数组元素类型 `float32,uint8,...`\n",
    "|`a.shape`|数组形状 `(m,n,o,...)`\n",
    "|`a.size`|数组元素数\n",
    "|`a.itemsize`|每个元素占字节数\n",
    "|`a.nbytes`|所有元素占的字节\n",
    "|`a.ndim`|数组维度\n",
    "|2|**形状相关**\n",
    "|`a.flat`|所有元素的迭代器\n",
    "|`a.flatten()`|返回一个1维数组的复制\n",
    "|`a.ravel()`|返回一个1维数组，高效\n",
    "|`a.resize(new_size)`|改变形状\n",
    "|`a.swapaxes(axis1, axis2)`|交换两个维度的位置\n",
    "|`a.transpose(*axex)`|交换所有维度的位置\n",
    "|`a.T`|转置，`a.transpose()`\n",
    "|`a.squeeze()`| 去除所有长度为1的维度\n",
    "|3|**填充复制**\n",
    "|`a.copy()`| 返回数组的一个复制\n",
    "|`a.fill(value)`| 将数组的元组设置为特定值\n",
    "|4|**转化**\n",
    "|`a.tolist()`|将数组转化为列表\n",
    "|`a.tostring()`|转换为字符串\n",
    "|`a.astype(dtype)`|转化为指定类型\n",
    "|`a.byteswap(False)`|转换大小字节序\n",
    "|`a.view(type_or_dtype)`|生成一个使用相同内存，但使用不同的表示方法的数组\n",
    "|5|**复数**\n",
    "|`a.imag`|虚部\n",
    "|`a.real`|实部\n",
    "|`a.conjugate()`|复共轭\n",
    "|`a.conj()`|复共轭（缩写）\n",
    "|6|**保存**\n",
    "|`a.dump(file)`|将二进制数据存在file中\n",
    "|`a.dump()`|将二进制数据表示成字符串\n",
    "|`a.tofile(fid, sep=\"\",format=\"%s\")`|格式化ASCⅡ码写入文件\n",
    "|7|**查找排序**\n",
    "|`a.nonzero()`|返回所有非零元素的索引\n",
    "|`a.sort(axis=-1)`|沿某个轴排序\n",
    "|`a.argsort(axis=-1)`|沿某个轴，返回按排序的索引\n",
    "|`a.searchsorted(b)`|返回将b中元素插入a后能保持有序的索引值\n",
    "|8|**元素数学操作**\n",
    "|`a.clip(low, high)`|将数值限制在一定范围内\n",
    "|`a.round(decimals=0)`|近似到指定精度\n",
    "|`a.cumsum(axis=None)`|累加和\n",
    "|`a.cumprod(axis=None)`|累乘积\n",
    "|9|**约简操作**\n",
    "|`a.sum(axis=None)`|求和\n",
    "|`a.prod(axis=None)`|求积\n",
    "|`a.min(axis=None)`|最小值\n",
    "|`a.max(axis=None)`|最大值\n",
    "|`a.argmin(axis=None)`|最小值索引\n",
    "|`a.argmax(axis=None)`|最大值索引\n",
    "|`a.ptp(axis=None)`|最大值减最小值\n",
    "|`a.mean(axis=None)`|平均值\n",
    "|`a.std(axis=None)`|标准差\n",
    "|`a.var(axis=None)`|方差\n",
    "|`a.any(axis=None)`|只要有一个不为0，返回真，逻辑或\n",
    "|`a.all(axis=None)`|所有都不为0，返回真，逻辑与"

In [1]:
import numpy as np 
import time
from matplotlib.pyplot import axis



## 创建数组 

array:
arange :arange(start, stop=None, step=1, dtype=None)
产生一个在区间 \[start, stop) 之间，以 step 为间隔的数组，如果只输入一个参数，则默认从 0 开始，并以这个值为结束：

np.zeros/empty/ones:传入形状即可

empty_like, ones_like, zeros_like
empty_like(a)、ones_like(a)、zeros_like(a)
产生一个跟 a 大小一样，类型一样的对应数组

np.diag():对角阵

linspace:linspace(start, stop, N) 产生 N 个等距分布在 [start, stop\]间的元素组成的数组，包括 start, stop,第一个参数表示起始点、第二个参数表示终止点，第三个参数表示数列的个数

logspace：logspace(start, stop, N)、产生 N 个对数等距分布的数组，默认以10为底

identity：indentity(n, dtype=float64)产生一个 n 乘 n 的单位矩阵

reshape:可以创建一个改变了尺寸的新数组，原数组的shape保持不变
数组a和d其实共享数据存储内存区域，因此修改其中任意一个数组的元素都会同时修改另外一个数组的内容


In [12]:
a = np.array([1,2,3,4])
d = a.reshape((2,2))
print(a)
print(d)
print(np.diag((1,2,3)))# 创建对角阵
x = np.arange(10,19).reshape((3,3))
print(x)
print(np.diag(x)) #提取对角
print(np.diag(x,1)) #注意对角线的位置

[1 2 3 4]
[[1 2]
 [3 4]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[10 14 18]
[11 15]


## 向量化的优势 

In [5]:
a + 1

array([2, 3, 4, 5])

In [6]:
b = np.array([2, 3, 4, 5])
a + b

array([3, 5, 7, 9])

 compare  vectorization and for loop

In [11]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
tic = time.time()
c=np.dot(a,b)
toc = time.time()

print(c)
print("vectorization:" +str(1000*(toc-tic))+"ms")

c=0
tic = time.time()
for i in range(1000000):
    c=a[i]+b[i];
toc = time.time()
print(c)
print("vectorization:" +str(1000*(toc-tic))+"ms")

249910.36933394146
vectorization:69.00405883789062ms
1.550543941266711
vectorization:349.9951362609863ms


## random函数

In [2]:
np.random.rand(4,2)

array([[0.55743778, 0.08326764],
       [0.27658304, 0.69030943],
       [0.34477484, 0.29308865],
       [0.32284147, 0.11990476]])

In [3]:
demo_list = ['lenovo', 'sansumg','moto','xiaomi', 'iphone']
np.random.choice(demo_list,size=(3,3), p=[0.1,0.6,0.1,0.1,0.1])

array([['sansumg', 'xiaomi', 'iphone'],
       ['xiaomi', 'lenovo', 'sansumg'],
       ['moto', 'sansumg', 'sansumg']], dtype='<U7')

In [4]:
np.random.seed(3)
np.random.rand(5)

array([0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695])

In [5]:
np.random.seed(3)
np.random.rand(5)

array([0.5507979 , 0.70814782, 0.29090474, 0.51082761, 0.89294695])

In [7]:
a = np.arange(12)  
print(a)   
b = np.random.permutation(a)  
print (b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3  2  1  8  4  0  6  7  5 11  9 10]
